services:
  api:
    build: ./api
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      mysqlDatabase:
        condition: service_healthy
    env_file:
      - .env
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysqlDatabase
      MYSQL_PORT: "3306"
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:5555/api/auth/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysqlDatabase:
    image: mysql:9.3.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
